# Generated by Django 5.2 on 2025-05-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_likeproperty_property_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
