services:
  web:
    build: ./djangobnb_backend
    command: python manage.py runserver 0.0.0.0:8000 & celery -A djangobnb_backend worker --loglevel=info"
    volumes:
      - ./djangobnb_backend/:/usr/src/djangobnb_backend/
    user: "${UID}:${GID}"
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=djangobnb
  
  redis:
    image: redis:8.0.0-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: