# Generated by Django 5.2 on 2025-05-08 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('property', '0003_likeproperty_property_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='property.property'),
        ),
    ]
