# Generated by Django 5.2 on 2025-04-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_user_options_user_first_name_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
