import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./ui/fonts";
import styles from './layout.module.css';

import Navbar from "./components/navbar/Navbar"; 
import LoginModal from '@/app/components/modals/LoginModal';
import SignupModal from '@/app/components/modals/SignupModal';

export const metadata: Metadata = {
  title: "Django bnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const content =  (
      <p>Yo</p>
)
  
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbar />
        <div className={styles.div}>
          {children}
        </div>
        <LoginModal />
        <SignupModal />
      </body>
    </html>
  );
}
